config/routes.rb
Rails.application.routes.draw do

  root to: 'bookmarks#new'

  resources :bookmarks

  resources :sites

  get 'tags/:tag', to: 'bookmarks#index', as: :tag

  get '/home/autocomplete_tags', to: 'tags#autocomplete_tags', as: 'autocomplete_tags'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  validates_presence_of :url
  validate :url_must_be_valid

  acts_as_taggable
  belongs_to :site

  after_validation :generate_short_url
  before_create :get_metadata
  before_save :associate_with_site

  include Searchable
  searchable_by :title, :description
 
  def url_must_be_valid
  	self[:url] = "http://#{url}" unless url && url.start_with?('http')
    unless url =~ /^#{URI::regexp}$/
      errors.add(:url, "Invalid URL.")
    end
  end

  def generate_short_url
  	self[:short_url] = ShortURL.shorten(url) if url
  end

  def get_metadata
    page = MetaInspector.new(url) rescue nil
    if page
	    self[:title] = page.title
	    self[:description] = page.description
	    self.tag_list.add(page.meta['keywords'], parse: true)
	    self[:image_url] = page.image || page.images.first
	  end
  end

  def associate_with_site
  	self[:site_id] = Site.find_or_create_by(domain: PublicSuffix.parse(URI.parse(url).host).domain).id rescue nil
  end

end

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  module ClassMethods
    def searchable_by(*args)
      sql = args.map{|arg| "#{arg} LIKE :query OR"}.join(" ")[0..-4] #create the sql statement from the arguments specified, cut off the last OR
      scope :search, ->(q) do
        where("#{sql}", {query: "%#{q}%"})
      end
    end
  end
end

app/models/site.rb
class Site < ActiveRecord::Base
  validates_presence_of :domain
  include Searchable
  searchable_by "domain", "bookmarks.title", "bookmarks.description" #passing the join args as strings as some contain periods
  has_many :bookmarks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  # GET /bookmarks
  # GET /bookmarks.json

  
  def index
    if params[:tag]
      @bookmarks = Bookmark.tagged_with(params[:tag])
      @header = "Bookmarks tagged with: #{params[:tag]}"
    elsif params[:query]
      @bookmarks = Bookmark.tagged_with(params[:query], any: true, wild: true) | 
                   Bookmark.search(params[:query])
      @header = "Searching bookmarks by: #{params[:query]}"
    else
      @bookmarks = Bookmark.order('created_at DESC').all
      @header = "All bookmarks"
    end
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end


  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :description, :keywords, :url, :short_url, :image_url, :tag_list)
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    if params[:query]
      @sites = Bookmark.tagged_with(params[:query], any: true, wild: true).map(&:site) |
               Site.joins(:bookmarks).uniq.search(params[:query]).order(:domain)
      @header = "Searching sites by: #{params[:query]}"
    else
      @sites = Site.order(:domain).all
      @header = "All sites"
    end
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:domain)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def autocomplete_tags
  	query = params[:q]
    if query[-1,1] == " "
      query = query.gsub(" ", "")
      Tag.find_or_create_by_name(query)
    end
    @tags = ActsAsTaggableOn::Tag.all
    @tags = @tags.select { |v| v.name =~ /#{query}/i }
    respond_to do |format|
      format.json{ render :json => @tags.collect{|t| {:id => t.name, :name => t.name }} }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/bookmarks/_bookmark.html.haml
.bookmark-tile
  = link_to truncate(bookmark.title, length: 100), bookmark, style: 'padding:5px'
  %br
  = link_to(image_tag(bookmark.image_url || image_url('default-bookmark2.png')), bookmark)
  %br
  = raw bookmark.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') 
 

app/views/bookmarks/_form.html.haml
= form_for(@bookmark, :html => { :class => 'form-horizontal' }) do |f|
  .control-group
    = f.text_field :url, class: 'form-control', placeholder: 'Paste or drag a URL to create a bookmark..'
  %br
  %br
  .control-group
    = f.label 'Add tags:' 
    .controls
      = f.text_field :tag_list, class: 'tag-select', placeholder: "Enter tags", data: { saved: f.object.tags.map{|t| {id: t.name, name: t.name}}.to_json, url: autocomplete_tags_path }
      %small
        Additional tags will be pulled from the site's metadata.

  %br
    %span.input-group-btn
    = f.submit nil, :class => 'btn btn-orange'
  

app/views/bookmarks/edit.html.haml
- model_class = Bookmark
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/bookmarks/index.html.haml
.row
  = form_tag bookmarks_path, method: :get do
    .control-group
      .input-group
        = text_field_tag :query, params[:query], class: 'form-control', placeholder: 'Search bookmarks by title, description or tags..'
        %span.input-group-btn
          = submit_tag "Search", :class => 'btn btn-orange'
.row
  .page-header
    %h1
      = @header
.row
  #tag_cloud
    - tag_cloud Bookmark.tag_counts, %w{s m l} do |tag, css_class|
      =link_to(tag.name, tag_path(tag.name), class: css_class)
%br
.row
  .to-mason
    = render @bookmarks
  .clearfix

app/views/bookmarks/new.html.haml
- model_class = Bookmark
.jumbotron
  .page-header
    %h1
      Bookmark.io
  = render :partial => "form"

app/views/bookmarks/show.html.haml
- model_class = Bookmark
.page-header
  %h1
    = best_in_place @bookmark, :title, :type => :textarea

.container
  .row
    .col-md-6
      = link_to(image_tag(@bookmark.image_url || image_url('default-bookmark2.png'), class: 'bookmark-show-image' ), @bookmark.url)
    .col-md-6
      %p
        = link_to("View Page", @bookmark.url, class: "btn btn-large btn-orange")
      %p
        %strong= model_class.human_attribute_name(:description) 
        %br
        = best_in_place @bookmark, :description, :type => :textarea
        %br
        %br
      %p
        %strong= "Tags"
        %br
        = raw @bookmark.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')

        %br
        %br
      %p
        %strong= Site
        %br
        = link_to @bookmark.site.domain, @bookmark.site if @bookmark.site
        %br
        %br
      %p
        %strong= model_class.human_attribute_name(:url) 
        %br
        = link_to("#{@bookmark.url}", @bookmark.url)
        %br
        %br
      %p
        %strong= model_class.human_attribute_name(:short_url)
        %br
        = link_to("#{@bookmark.short_url}", @bookmark.short_url)
        %br
        %br
 
      .form-actions
        = link_to t('.destroy', :default => t("helpers.links.destroy")), bookmark_path(@bookmark), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmarkio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Bookmarkio"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

  %body
    .container.content
      .masthead.clearfix
        .inner
          - unless current_page?(root_path)
            %h3.masthead-brand
              = link_to "Bookmark.io", root_path
          %ul.nav.masthead-nav
            %li{class: ('active' if current_page?(root_path))} 
              = link_to 'Home', '/'
            %li{class: ('active' if current_page?(bookmarks_path))} 
              = link_to 'Bookmarks', bookmarks_path
            %li{class: ('active' if current_page?(sites_path))} 
              = link_to 'Sites', sites_path

      .container
        = yield

      .mastfoot
        .inner
          %p
            = link_to "Bookmarkio", "http://github.com/bhaity/bookmarkio"
            by
            = link_to  "bhaity", "http://github.com/bhaity/"
  

app/views/sites/_form.html.haml
= form_for @site, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :domain, :class => 'control-label'
    .controls
      = f.text_field :domain, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), sites_path, :class => 'btn'

app/views/sites/edit.html.haml
- model_class = Site
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/sites/index.html.haml
.row
  = form_tag sites_path, method: :get do
    .control-group
      .input-group
        = text_field_tag :query, params[:query], class: 'form-control', placeholder: 'Search sites by domain, bookmark title or tags..'
        %span.input-group-btn
          = submit_tag "Search", :class => 'btn btn-orange'
.row
  .page-header
    %h1
      = @header
.row{style: 'padding-top:50px;'}
  - @sites.each do |site|
    = link_to site.domain + " (#{site.bookmarks.count})", site_path(site), class:'lead'
    %br

app/views/sites/new.html.haml
- model_class = Site
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/sites/show.html.haml
.page-header
  %h1
    = best_in_place @site, :domain

.form-actions
  = link_to t('.destroy', :default => t("helpers.links.destroy")), site_path(@site), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure? This will permanently delete the site and all bookmarks associated with it')) }, :class => 'btn btn-danger'
%br
%br
.row
  .to-mason
    = render @site.bookmarks
  .clearfix

app/views/tags/autocomplete_TAG.html.haml
%h1 Tags#autocomplete_TAG
%p Find me in app/views/tags/autocomplete_TAG.html.haml